name: game_lovers_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  google_fonts: ^2.2.0
  oktoast: ^3.1.5
  provider: ^6.0.2
  responsive_framework: ^0.1.5
  mocktail: ^0.2.0
  drift: ^1.3.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  internet_connection_checker: ^0.0.1+3
  cached_network_image: ^3.2.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  drift_dev: ^1.3.0
  build_runner: ^2.1.7
  bloc_test: ^9.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logoIcon.png"
